local constants = require('lolloArrivalsDeparturesPredictor.constants')

-- LOLLO NOTE from UG on regex
-- Hi. This is what we do with the expr and replace if the label is set to custom filter:
--[[
    std::regex_replace(
        text,
        std::regex(expr),
        replace,
        std::regex_constants::format_sed | std::regex_constants::format_no_copy
    );
]]
-- with the 4th parameter "flags", we set the format to the "Sed" format
-- it is possible that the C++ implementation does not support the full regexp capabilities
-- aside from that we do not do anything special with the input strings

--[[
    https://www.cplusplus.com/reference/regex/regex_replace/
    https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sed.html#tag_20_116_13_03
    https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=net-6.0
    https://www.cplusplus.com/reference/regex/regex_constants/
]]

-- for platform bouards, stick this in the model editor under "options - config - name"
-- local _testText = "@_track_@88@_1_@Brignole@_2_@12:25@_3_@Ü Bigottu@_4_@1:11@_clock_@01:12:20@"
-- for station boards, stick this in the model editor under "options - config - name"
-- local _testText = "@_header_@Departures@_footer_@VeryVeryVeryLongLongLongTextTextText@_1_@To@_2_@Platform@_3_@TimeLong@_4_@Brignole@_5_@2@_6_@1:50@_7_@Torino Porta Nuova Molto molto molto lungo@_8_@21@_9_@19:42@_10_@Sestri Levante@_11_@12@_12_@19:48@_13_@Milano Centrale@_14_@24@_15_@19:59@_16_@Milano Centrale@_17_@24@_18_@20:59@_19_@Milano Centrale@_20_@24@_21_@21:59@_22_@Milano Centrale@_23_@24@_24_@22:59@_25_@Ventimiglia - Marseille@_26_@24@_27_@23:59@_clock_@01:12:20@"

local function getRegexParams(counter)
    return {
        -- text = "@1SELECT_PART_1@2SELECT_PART_2@",
        -- text = "@1SEL_P1@2SEL_P2@31:50@4Brignole@52@61:50@7Porta Nuova@824@923:59@",
        -- expr = "@2([a-zA-Z0-9_]+)@", -- works
        -- expr = "@1([a-zA-Z0-9_]+)@", -- works
        -- expr = "@1([^@]+)@", -- works best
        -- expr = "@" .. counter .. "([^@]+)@",
        expr = "@_" .. counter .. "_@([^@]+)@",
        replace="\\1", -- works
    }
end

local utils = {
    getManchesterMetrolinkLabelList = function()
        return {
            labels = {
                -- face A
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = { 0.97, 0.1, },
                    transf = { 1, 0, 0, 0, 0, -0.139, 0.99, 0, 0, -0.99, -0.139, 0, 0.4, -0.09, 4.35, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = { 0.97, 0.1, },
                    transf = { 1, 0, 0, 0, 0, -0.139, 0.99, 0, 0, -0.99, -0.139, 0, 0.4, -0.09, 4.25, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "CENTER",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = { 1.27, 0.14, },
                    transf = { 1, 0, -0, 0, 0, -0.139, 0.99, 0, 0, -0.99, -0.139, 0, 0.4, -0.07, 4.1, 1, },
                    type = "NAME",
                    verticalAlignment = "BOTTOM",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = { 0.3, 0.1, },
                    transf = { 1, 0, -0, 0, 0, -0.139, 0.99, 0, 0, -0.99, -0.139, 0, 1.37, -0.09, 4.35, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = { 0.3, 0.1, },
                    transf = { 1, 0, -0, 0, 0, -0.139, 0.99, 0, 0, -0.99, -0.139, 0, 1.37, -0.08, 4.25, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- face B
                {
                	alignment = "LEFT",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	color = { 1, 0.541, 0, },
                	filter = "CUSTOM",
                	fitting = "CUT",
                	nLines = 1,
                	params = getRegexParams(1),
                	renderMode = "EMISSIVE",
                	size = { 0.97, 0.1, },
                	transf = { -1, 0, -0, 0, 0, 0.139, 0.99, 0, 0, 0.99, -0.139, 0, 1.66, 0.09, 4.35, 1, },
                	type = "NAME",
                	verticalAlignment = "CENTER",
                },
                {
                	alignment = "LEFT",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	color = { 1, 0.541, 0, },
                	filter = "CUSTOM",
                	fitting = "CUT",
                	nLines = 1,
                	params = getRegexParams(3),
                	renderMode = "EMISSIVE",
                	size = { 0.97, 0.1, },
                	transf = { -1, 0, -0, 0, 0, 0.139, 0.99, 0, 0, 0.99, -0.139, 0, 1.66, 0.08, 4.25, 1, },
                	type = "NAME",
                	verticalAlignment = "CENTER",
                },
                {
                	alignment = "CENTER",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	color = { 1, 0.541, 0, },
                	filter = "CUSTOM",
                	fitting = "CUT",
                	nLines = 1,
                	params = getRegexParams(constants.nameTags.clock),
                	renderMode = "EMISSIVE",
                	size = { 1.27, 0.14, },
                	transf = { -1, 0, -0, 0, 0, 0.139, 0.99, 0, 0, 0.99, -0.139, 0, 1.66, 0.07, 4.1, 1, },
                	type = "NAME",
                	verticalAlignment = "BOTTOM",
                },
                {
                	alignment = "RIGHT",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	color = { 1, 0.541, 0, },
                	filter = "CUSTOM",
                	fitting = "CUT",
                	nLines = 1,
                	params = getRegexParams(2),
                	renderMode = "EMISSIVE",
                	size = { 0.3, 0.1, },
                	transf = { -1, 0, -0, 0, 0, 0.139, 0.99, 0, 0, 0.99, -0.139, 0, 0.7, 0.09, 4.35, 1, },
                	type = "NAME",
                	verticalAlignment = "CENTER",
                },
                {
                	alignment = "RIGHT",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	color = { 1, 0.541, 0, },
                	filter = "CUSTOM",
                	fitting = "CUT",
                	nLines = 1,
                	params = getRegexParams(4),
                	renderMode = "EMISSIVE",
                	size = { 0.3, 0.1, },
                	transf = { -1, 0, -0, 0, 0, 0.139, 0.99, 0, 0, 0.99, -0.139, 0, 0.7, 0.08, 4.25, 1, },
                	type = "NAME",
                	verticalAlignment = "CENTER",
                },
            },
        }
    end,
    getPlatformBoardLabelList = function()
        local _zed0 = 2.67
        local _dZed = -0.1
        local function zed(counter)
            return _zed0 + math.floor((counter - 1) / 2) * _dZed
        end

        local _sizeLeft = {10, 1}
        local _sizeMid = {3, 1}
        local _sizeRight = { 3, 1, }
        local _yShiftA = -0.12
        local _yShiftB = 0.12

        return {
            labels = {
                -- face A
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.track),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- face B
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.track),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = {4, 1},
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.65, _yShiftB, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.55, _yShiftB, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.55, _yShiftB, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
            },
        }
    end,
    getStationBoardLabelList = function()
        local _zed0 = 3.65
        local _dZed = -0.1
        local function zed(counter)
            return _zed0 + math.floor((counter - 1) / 3) * _dZed
        end

        local _sizeLeft = {6.4, 1}
        local _sizeMid = {3, 1}
        local _sizeRight = { 3, 1, }

        return {
            labels = {
                -- {
                -- 	alignment = "LEFT",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM", -- 'NONE', 'NUMBER', 'CUSTOM'
                -- 	-- filter = 'NONE',
                -- 	fitting = "SCALE",
                -- 	font = 'Lato', -- 'Lato', 'Noto'
                -- 	nLines = 2,
                -- 	params = {
                -- 		-- expr = '/[a-zA-Z]+/gm',
                -- 		-- expr = '/[A-S]+/gm',
                -- 		-- expr = '[A-S]',
                -- 		expr = "([a-zA-Z-]*)",
                -- 		-- replace = 'KOK\\0MNM\\1 UNO\\2DUE',
                -- 		-- replace = 'KOK',
                -- 		replace = '\\0',
                -- 	},
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1, 1, },
                -- 	transf = { 1, 0, 0, 0,
                -- 		0, 0, 1, 0,
                -- 		0, -1, 0, 0,
                -- 		-0.5, -0.07, 4.0, 1,
                -- 	},
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.header),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    -- size = { 1.02, 0.15, },
                    size = {4, 1},
                    -- transf = { 1, 0, -0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.12, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(7),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(7), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(8),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(8), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(9),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(9), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(10),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(10), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(11),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(11), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(12),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(12), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(13),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(13), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(14),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(14), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(15),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(15), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(16),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(16), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(17),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(17), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(18),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(18), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(19),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(19), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(20),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(20), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(21),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(21), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(22),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(22), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(23),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(23), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(24),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(24), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(25),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(25), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(26),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(26), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(27),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(27), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- {
                -- 	alignment = "CENTER",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM",
                -- 	fitting = "CUT",
                -- 	nLines = 1,
                -- 	params = getRegexParams(constants.nameTags.clock),
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1.02, 0.15, },
                -- 	transf = { 1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                	alignment = "CENTER",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	-- color = { 1, 1, 1, },
                    color = { 1, 0.54, 0, },
                	-- filter = "CUSTOM",
                    filter = "NONE",
                	fitting = "CUT",
                	nLines = 2,
                	-- params = getRegexParams(constants.nameTags.footer),
                	renderMode = "EMISSIVE",
                	size = {5.5, 1},
                    transf = { 0.2, 0, 0, 0,  0, 0, 0.2, 0,  0, 1, 0, 0,  -0.55, -0.06, 2.6, 1, },
                	-- type = "NAME",
                    type = "COMPANY_NAME",
                	verticalAlignment = "CENTER",
                },
            },
        }
    end,
    getStationWideBoardLabelList = function()
        local _zed0 = 3.65
        local _dZed = -0.1
        local function zed(counter)
            return _zed0 + math.floor((counter - 1) / 3) * _dZed
        end

        local _sizeLeft = {15, 1}
        local _sizeMid = {3, 1}
        local _sizeRight = { 3, 1, }

        return {
            labels = {
                -- {
                -- 	alignment = "LEFT",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM", -- 'NONE', 'NUMBER', 'CUSTOM'
                -- 	-- filter = 'NONE',
                -- 	fitting = "SCALE",
                -- 	font = 'Lato', -- 'Lato', 'Noto'
                -- 	nLines = 2,
                -- 	params = {
                -- 		-- expr = '/[a-zA-Z]+/gm',
                -- 		-- expr = '/[A-S]+/gm',
                -- 		-- expr = '[A-S]',
                -- 		expr = "([a-zA-Z-]*)",
                -- 		-- replace = 'KOK\\0MNM\\1 UNO\\2DUE',
                -- 		-- replace = 'KOK',
                -- 		replace = '\\0',
                -- 	},
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1, 1, },
                -- 	transf = { 1, 0, 0, 0,
                -- 		0, 0, 1, 0,
                -- 		0, -1, 0, 0,
                -- 		-0.5, -0.07, 4.0, 1,
                -- 	},
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.header),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    -- size = { 1.02, 0.15, },
                    size = {4, 1},
                    -- transf = { 1, 0, -0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.6, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(7),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(7), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(8),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(8), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(9),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(9), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(10),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(10), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(11),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(11), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(12),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(12), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(13),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(13), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(14),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(14), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(15),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(15), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(16),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(16), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(17),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(17), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(18),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(18), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(19),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(19), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(20),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(20), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(21),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(21), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(22),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(22), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(23),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(23), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(24),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(24), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(25),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -1.01, -0.06, zed(25), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(26),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.35, -0.06, zed(26), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(27),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.7, -0.06, zed(27), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- {
                -- 	alignment = "CENTER",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM",
                -- 	fitting = "CUT",
                -- 	nLines = 1,
                -- 	params = getRegexParams(constants.nameTags.clock),
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1.02, 0.15, },
                -- 	transf = { 1, 0, -0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                	alignment = "CENTER",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	-- color = { 1, 1, 1, },
                    color = { 1, 0.54, 0, },
                	-- filter = "CUSTOM",
                    filter = "NONE",
                	fitting = "CUT",
                	nLines = 2,
                	-- params = getRegexParams(constants.nameTags.footer),
                	renderMode = "EMISSIVE",
                	size = {10, 1},
                    transf = { 0.2, 0, 0, 0,  0, 0, 0.2, 0,  0, 1, 0, 0,  -1.01, -0.06, 2.6, 1, },
                	-- type = "NAME",
                    type = "COMPANY_NAME",
                	verticalAlignment = "CENTER",
                },
            },
        }
    end,
    -- LOLLO NOTE if a construction contains models without bounding info and collider,
    -- it will still detect collisions with them. With these, we avoid that problem.
    getVoidBoundingInfo = function()
        return {} -- this seems the same as the following
        -- return {
        --     bbMax = { 0, 0, 0 },
        --     bbMin = { 0, 0, 0 },
        -- }
    end,
    getVoidCollider = function()
        -- return {
        --     params = {
        --         halfExtents = { 0, 0, 0, },
        --     },
        --     transf = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, },
        --     type = 'BOX',
        -- }
        return {
            type = 'NONE'
        }
    end,
}

return utils
